[book]
authors = ["Seb Blair (CompEng0001)"]
language = "en"
multilingual = false
src = "content"
title = "MD-Book Template for UoG"

[output.html]
highlightjs = false  # disable if not already
mathjax-support = true
git-repository-url = "https://github.com/uniofgreenwich/MD_Book_Template"
edit-url-template = "https://github.com/uniofgreenwich/MD_Book_Template/edit/main/{path}"
additional-css = [
    "./theme/pagetoc.css", 
    "./theme/css/mdbook-admonish.css",
    "./theme/css/code.css",
    "./theme/css/terminal.css",
    "./theme/css/output.css",
    "./theme/css/mdbook-admonish.css",
]
additional-js  = ["./theme/pagetoc.js", "./theme/highlightjs-line-numbers.js"]

[output.html.print]
enable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true

[preprocessor.gitinfo]
enable = true
template = "Last updated: {{date}} {{sep}} Commit: {{hash}}"
font-size = "0.8em"
separator = "|"
date-format = "%A %d %B %Y"
time-format = "@ %H:%M:%S"
after = ["embedify"]

[preprocessor.embedify]
custom-templates-folder = "theme/assets/templates"
before = ["links"]
scroll-to-top.enable = true
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️ by [CompEng0001](https://github.com/CompEng0001)"

announcement-banner.enable = false
announcement-banner.id = "0.2.15"
announcement-banner.message = "*Version **0.2.15** now has relased, check it out [here](https://github.com/MR-Addict/mdbook-embedify/releases/tag/0.2.15).*"

giscus.enable = false
giscus.repo = "MR-Addict/mdbook-embedify"
giscus.repo-id = "R_kgDOLCxX0Q"
giscus.category = "General"
giscus.category-id = "DIC_kwDOLCxX0c4CdGx-"
giscus.reactions-enabled = "1"
giscus.theme = "book"
giscus.lang = "en"
giscus.loading = "lazy"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0" # do not edit: managed by `mdbook-admonish install`
before = ["embedify"]
renderer.test.render_mode = "html"

[preprocessor.admonish.directive.custom.code]
icon = "./theme/code-square.svg"
color = "#24ab38"
aliases = ["code"]

[preprocessor.admonish.directive.custom.terminal]
icon = "./theme/terminal.svg"
color = "#76727B"
aliases = ["cli","cmd"]

[preprocessor.admonish.directive.custom.output]
icon = "./theme/output.svg"
color = "#72879C"

[preprocessor.quiz]
before = ["admonish"]
fullscreen = false
show-bug-reporter = true

[preprocessor.pagetoc]