name: deploy to github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install segno

      - name: Setup mdBook
        uses: jontze/action-mdbook@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-toc: true
          use-admonish: true
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build and install mdbook-quiz from source
        run: cargo install mdbook-quiz --version 0.4.0
      
      - name: Install mdbook-gitinfo
        run: |
          curl -sSL https://github.com/CompEng0001/mdbook-gitinfo/releases/download/v0.1.2/mdbook-gitinfo-linux.tar.gz | tar -xz
          chmod +x mdbook-gitinfo-linux
          mv mdbook-gitinfo-linux ~/.cargo/bin/mdbook-gitinfo

      - name: Install mdbook-embedify
        run: |
          curl -sSL -o embedify.zip https://github.com/MR-Addict/mdbook-embedify/releases/download/0.2.17/mdbook-embedify-0.2.17-x86_64-unknown-linux-gnu.zip
          unzip embedify.zip
          chmod +x mdbook-embedify-0.2.17-x86_64-unknown-linux-gnu/mdbook-embedify
          mv mdbook-embedify-0.2.17-x86_64-unknown-linux-gnu/mdbook-embedify ~/.cargo/bin/

      - name: Show mdbook version
        run: mdbook --version
      - name: Show toc version
        run: mdbook-toc --version
      - name: Show admonish version
        run: mdbook-admonish --version
      - name: Show quiz version
        run: mdbook-quiz --version
      - name: Show embedify version
        run: mdbook-embedify --version
      - name: Show gitinfo version
        run: mdbook-gitinfo --version

      - name: Generate QR code
        env:
          REPO_NAME: ${{ github.repository }}
        run: python .github/qrgen.py

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: "./book"