name: deploy to github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install segno

      - name: Setup mdBook
        uses: jontze/action-mdbook@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-toc: true
          use-admonish: true
      
      - name: Install mdbook-quiz
        run: |
          curl -sSL https://github.com/cognitive-engineering-lab/mdbook-quiz/releases/download/v0.3.10/mdbook-quiz_x86_64-unknown-linux-gnu_bare.tar.gz | tar -xz
          chmod +x mdbook-quiz
          mv mdbook-quiz ~/.cargo/bin/
      
      - name: Install mdbook-embedify
        run: |
          curl -sSL -o embedify.zip https://github.com/MR-Addict/mdbook-embedify/releases/download/0.2.15/mdbook-embedify-0.2.15-x86_64-unknown-linux-gnu.zip
          unzip embedify.zip
          chmod +x mdbook-embedify-0.2.15-x86_64-unknown-linux-gnu/mdbook-embedify
          mv mdbook-embedify-0.2.15-x86_64-unknown-linux-gnu/mdbook-embedify ~/.cargo/bin/

      - name: Show mdbook version
        run: mdbook --version
      - name: Show toc version
        run: mdbook-toc --version
      - name: Show admonish version
        run: mdbook-admonish --version
      - name: Show quiz version
        run: mdbook-quiz --version
      - name: Show embedify version
        run: mdbook-embedify --version

      - name: Generate QR code
        env:
          REPO_NAME: ${{ github.repository }}
        run: python .github/qrgen.py

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: "./book"